apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  labels:
    role: alert-rules
data:
  alert.rules: |
    groups:
    - name: example
      rules:
      - alert: HighMemoryUsage
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Node memory is low"
          description: "Node memory is below 10% for more than 5 minutes."
