apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-scrape-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'elasticsearch'
        static_configs:
          - targets: ['elasticsearch:9200']
      - job_name: 'app-vm1'
        static_configs:
          - targets: ['app-vm1-service:80']
      - job_name: 'db-vm1'
        static_configs:
          - targets: ['db-vm1-service:5432']
      - job_name: 'web-vm1'
        static_configs:
          - targets: ['web-vm1-service:8080']
