apiVersion: v1
kind: Service
metadata:
  name: nagios-service
  labels:
    app: nagios-core
spec:
  type: NodePort
  selector:
    app: nagios-core
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Pode ser qualquer porta entre 30000-32767
