apiVersion: batch/v1
kind: CronJob
metadata:
  name: logrotate
spec:
  schedule: "*/10 2-4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: logrotate
            image: appropriate/curl
            command: ["/usr/sbin/logrotate", "/etc/logrotate.conf"]
          restartPolicy: OnFailure
