- name: Deploy NTPD
  hosts: all
  become: true
  tasks:
    - name: Ensure ntp is installed
      apt:
        name: ntp
        state: present

    - name: Configure NTP
      copy:
        dest: /etc/ntp.conf
        content: |
          restrict default kod nomodify notrap nopeer noquery
          restrict -6 default kod nomodify notrap nopeer noquery
          restrict 127.0.0.1
          restrict -6 ::1
          server 192.168.0.252 minpoll 4 maxpoll 8
          server 192.168.0.251 minpoll 4 maxpoll 8
          server 192.168.0.0 # local clock
          fudge 192.168.0.0 stratum 10
          driftfile /var/lib/ntp/drift
          keys /etc/ntp/keys

    - name: Restart NTP service
      service:
        name: ntp
        state: restarted
