replicaCount: 3
image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 7.10.2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9200
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
elasticsearch:
  password: admin
